version: '3.9'

services:
  database:
    container_name: cloudStorageDB
    image: 'mysql:latest'
    # restart: on-failure
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: mysql
       MYSQL_DATABASE: netology
  cloudstorage:
    build: .
    links:
      - database
    # restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/netology
    depends_on:
      - database
  front:
    build:
      context: netology-diplom-frontend
      dockerfile: Dockerfile
    container_name: frontEnd

    ports:
      - '8080:8080'